/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/predict-profile`; params?: Router.UnknownInputParams; } | { pathname: `/predict`; params?: Router.UnknownInputParams; } | { pathname: `/swap`; params?: Router.UnknownInputParams; } | { pathname: `/trade`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/predict-market/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/predict-position/[conditionId]`, params: Router.UnknownInputParams & { conditionId: string | number; } } | { pathname: `/predict-sport/[sport]/[slug]`, params: Router.UnknownInputParams & { sport: string | number;slug: string | number; } } | { pathname: `/trade/[symbol]`, params: Router.UnknownInputParams & { symbol: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/predict-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/predict`; params?: Router.UnknownOutputParams; } | { pathname: `/swap`; params?: Router.UnknownOutputParams; } | { pathname: `/trade`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/predict-market/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/predict-position/[conditionId]`, params: Router.UnknownOutputParams & { conditionId: string; } } | { pathname: `/predict-sport/[sport]/[slug]`, params: Router.UnknownOutputParams & { sport: string;slug: string; } } | { pathname: `/trade/[symbol]`, params: Router.UnknownOutputParams & { symbol: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/predict-profile${`?${string}` | `#${string}` | ''}` | `/predict${`?${string}` | `#${string}` | ''}` | `/swap${`?${string}` | `#${string}` | ''}` | `/trade${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/predict-profile`; params?: Router.UnknownInputParams; } | { pathname: `/predict`; params?: Router.UnknownInputParams; } | { pathname: `/swap`; params?: Router.UnknownInputParams; } | { pathname: `/trade`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/predict-market/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/predict-position/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/predict-sport/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/trade/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/predict-market/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/predict-position/[conditionId]`, params: Router.UnknownInputParams & { conditionId: string | number; } } | { pathname: `/predict-sport/[sport]/[slug]`, params: Router.UnknownInputParams & { sport: string | number;slug: string | number; } } | { pathname: `/trade/[symbol]`, params: Router.UnknownInputParams & { symbol: string | number; } };
    }
  }
}
